### PR TITLE
Add git global configuration option

### PR DESCRIPTION
**Pull request by maksonlee**

### CODE REVIEW

**Comment by maksonlee** [comment]
JENKINS-32381

**Comment by rsandell** [comment]
Manipulating the global state of a slave like this is very dangerous as it leaves the slave with different configurations after the job has finished and can cause issues for other jobs running after.
Not to mention the security hole of someone being able to insert malicious configurations on slaves or master.

This belongs more at the slave configuration level, be configured by the admin and run on slave startup either in a separate plugin or maybe more appropriate the git or git-client plugin.

**Comment by rsandell** [comment]
If this was a feature that added local git config to the workspace it would be a different conversation.

**Comment by maksonlee** [comment]
Thanks for reply, but user can still change global git configuration in build step by executing shell command, right?

**Comment by rsandell** [comment]
Yes that's true. If git is installed on the slave (the git plugin could for example use jgit instead of cli git) but the repo plugin must have a git cli client available. So you're right; the "security hole" is there even without this pr added :)

**Comment by maksonlee** [comment]
And in our case, we are running jobs in docker cloud, slave would be deleted after job run is done and recreate from docker image on the next job request, so any manipulates to slave wouldn't be persistent.

**Comment by rsandell** [comment]
Far from everyone is running ephemeral slaves

**Comment by maksonlee** [comment]
Is it okay to set XDG_CONFIG_HOME to $WORKSPACE/.config only when running repo command, then we can put all custom git configurations into $WORKSPACE/.config/git /config file?

**Pull request closed without merging**
