### PR TITLE
Add option for --first-parent in changelog

### PR DESCRIPTION
**Pull request by onionjake**
This adds an option to select whether or not --first-parent is
passed to "git log" when determining the changelog.  The default
value is to include it.

### CODE REVIEW

**Comment by rsandell** [comment]
Configured jobs before this change will default to not have --first-parent. Because when the job is read from disk the first-parent field is missing and so will be set to the boolean default which is false.

**Comment by onionjake** [comment]
@rsandell I can reverse the logic so if it is checked `--first-parent` is excluded.  That should keep the same behavior for already configured jobs.

**Comment by rsandell** [comment]
Reverse logic is usually hard to grok. But in this case it might be OK.

You could also make the field into a Boolean reference and add a readResolve that would check if it is null and in that case set it to true, so old configs get converted, or check for null in the get and return true.

**Comment by onionjake** [comment]
I've renamed the parameter and reversed the logic.  Hopefully it isn't too confusing.

**Pull request merged**
