### PR TITLE
Fix invalid platform flag issue

### PR DESCRIPTION
**Pull request by maksonlee**
Change-Id: I46f02494f90719ca89db2a1722cd5ed9a1951f18

### CODE REVIEW

**Comment by rsandell** [comment]
is there an issue number for this? Your title suggests that there is an issue here?

**Comment by erictsai53** [comment]
All of our repo jobs are dead with 1.12.0.
Platform column are all empty by default.
This line is added in job configuration: "<manifestPlatform/>"

[repo] $ repo init -u ssh://****** -b ****** -m ******.xml -p  --current-branch --no-tags
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
Get ***********
fatal: invalid platform flag
java.io.IOException: Could not checkout
	at hudson.plugins.repo.RepoScm.checkout(RepoScm.java:850)
	at hudson.scm.SCM.checkout(SCM.java:505)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1205)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Skipped archiving because build is not successful

**Comment by zwx168238** [comment]
we got the same issue after upgrade repo plugin 1.12.0 , as workaround we must set platform value by hand

so , what's the plan to release 1.13.0 .

**Comment by rsandell** [comment]
@erictsai53 @zwx168238 is there a ticket number? And does this proposed fix solve the issue?

**Comment by shadamik** [comment]
This bugfix seem inconsistent with the rest of the code. All other webform params are returned with Util.fixEmptyAndTrim() to make sure they are null if empty.

I would prefer
```java
this.manifestPlatform = Util.fixEmptyAndTrim(manifestPlatform);
```
What do you think?

**Comment by maksonlee** [comment]
> This bugfix seem inconsistent with the rest of the code. All other webform params are returned with Util.fixEmptyAndTrim() to make sure they are null if empty.
> 
> I would prefer
> 
> ```java
> this.manifestPlatform = Util.fixEmptyAndTrim(manifestPlatform);
> ```
> 
> What do you think?
Done.

**Pull request merged**
