### PR TITLE
Add missing repo options; specifying platform, init --submodules and fetch --fetch-submodules, noTags and currentBranch

### PR DESCRIPTION
**Pull request by Typz**
Support some missing repo flags/options:
* Allow specifying platform in `repo init`
* Allow handling submodules (`repo init --submodules` and `repo fetch --fetch-submodules`)
* Apply `noTags` and `currentBranch` to repo init as well

### CODE REVIEW

**Comment by rsandell** [comment]
I was hoping to get some time to convert all the settings into traits (like github branch source and git plugins have). Maybe I get some time tomorrow or next week to do that. How important is it to get these settings in or can it wait a bit and get converted to traits?

**Comment by Spinus1** [comment]
Hello  @Typz  @rsandell, will it be possible to add an option to control whether to use or not the flag "--no-repo-verify"?
Surrently is hardcoded in src/main/java/hudson/plugins/repo/RepoScm.java when you pass repoUrl, but with some repo version "--no-repo-verify" is not working at all.

Thanks,
Alessio

**Comment by Typz** [comment]
> I was hoping to get some time to convert all the settings into traits (like github branch source and git plugins have). Maybe I get some time tomorrow or next week to do that. How important is it to get these settings in or can it wait a bit and get converted to traits?

Sorry for the late reply. Did you have the time to  make this change?

It is a quite important feature (actually, last one before we can fully rely on the plugin instead of plain old 'sh' steps), but we can wait a few days more.

So if you are confident your change will be ready soon, I don't mind waiting; but I would prefer not taking the chance to delay more than a few days/weeks (roughly no more end of 2019).

**Comment by rsandell** [comment]
I've started to work on it, but it's going slower than I thought. So I'll see if I can merge and release this first as I will probably not be done this week.

**Pull request merged**
